package querycraft.util;

import querycraft.model.ColumnInfo;
import querycraft.model.QueryResult;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.sql.Types;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * Utility class for generating SQL INSERT statements from query results.
 */
public class SqlInsertGenerator {

    private static final int DEFAULT_BATCH_SIZE = 1000;

    /**
     * Generate SQL INSERT statements from query result.
     */
    public static void generate(QueryResult result, File file, String tableName) throws IOException {
        generate(result, file, tableName, DEFAULT_BATCH_SIZE, true);
    }

    /**
     * Generate SQL INSERT statements with options.
     */
    public static void generate(QueryResult result, File file, String tableName,
                                 int batchSize, boolean useTransaction) throws IOException {

        try (Writer writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {

            List<ColumnInfo> columns = result.getColumns();

            if (columns.isEmpty()) {
                writer.write("-- No columns found in result set\n");
                return;
            }

            // Write header comment
            writer.write("-- Generated by QueryCraft\n");
            writer.write("-- Generated at: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()) + "\n");
            writer.write("-- Source table: " + tableName + "\n");
            writer.write("-- Row count: " + result.getRowCount() + "\n");
            writer.write("\n");

            // Start transaction
            if (useTransaction) {
                writer.write("BEGIN TRANSACTION;\n\n");
            }

            // Generate INSERT statements
            List<Object[]> rows = result.getRows();
            String insertPrefix = buildInsertPrefix(tableName, columns);

            for (int i = 0; i < rows.size(); i++) {
                if (i > 0 && i % batchSize == 0) {
                    writer.write("\n");
                }

                Object[] row = rows.get(i);
                String values = buildValuesClause(row, columns);
                writer.write(insertPrefix + values + ";\n");
            }

            // End transaction
            if (useTransaction) {
                writer.write("\nCOMMIT;\n");
            }
        }
    }

    /**
     * Generate batch INSERT statements (multiple VALUES per INSERT).
     */
    public static void generateBatchInserts(QueryResult result, File file, String tableName,
                                            int rowsPerInsert) throws IOException {

        try (Writer writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {

            List<ColumnInfo> columns = result.getColumns();

            if (columns.isEmpty()) {
                writer.write("-- No columns found in result set\n");
                return;
            }

            // Write header
            writer.write("-- Generated by QueryCraft\n");
            writer.write("-- Generated at: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()) + "\n");
            writer.write("-- Source table: " + tableName + "\n");
            writer.write("-- Row count: " + result.getRowCount() + "\n");
            writer.write("\n");

            writer.write("BEGIN TRANSACTION;\n\n");

            String insertPrefix = buildInsertPrefix(tableName, columns);
            List<Object[]> rows = result.getRows();

            for (int i = 0; i < rows.size(); i += rowsPerInsert) {
                writer.write(insertPrefix);

                int endIndex = Math.min(i + rowsPerInsert, rows.size());
                for (int j = i; j < endIndex; j++) {
                    if (j > i) {
                        writer.write(",\n");
                    }
                    writer.write(buildValuesClause(rows.get(j), columns));
                }

                writer.write(";\n\n");
            }

            writer.write("COMMIT;\n");
        }
    }

    private static String buildInsertPrefix(String tableName, List<ColumnInfo> columns) {
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO ").append(escapeIdentifier(tableName)).append(" (");

        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(escapeIdentifier(columns.get(i).getName()));
        }

        sb.append(") VALUES ");
        return sb.toString();
    }

    private static String buildValuesClause(Object[] row, List<ColumnInfo> columns) {
        StringBuilder sb = new StringBuilder();
        sb.append("(");

        for (int i = 0; i < row.length; i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(formatSqlValue(row[i], columns.get(i)));
        }

        sb.append(")");
        return sb.toString();
    }

    private static String formatSqlValue(Object value, ColumnInfo columnInfo) {
        if (value == null) {
            return "NULL";
        }

        int sqlType = columnInfo.getSqlType();

        // Numeric types - no quotes
        if (isNumericType(sqlType)) {
            return value.toString();
        }

        // Date/Time types
        if (value instanceof Date) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            return "'" + sdf.format((Date) value) + "'";
        }

        if (value instanceof java.sql.Date) {
            return "'" + value.toString() + "'";
        }

        if (value instanceof java.sql.Timestamp) {
            return "'" + value.toString() + "'";
        }

        if (value instanceof java.sql.Time) {
            return "'" + value.toString() + "'";
        }

        // Boolean
        if (value instanceof Boolean) {
            return value.toString();
        }

        // String and other types - escape and quote
        String strValue = value.toString();
        strValue = strValue.replace("'", "''"); // Escape single quotes
        return "'" + strValue + "'";
    }

    private static boolean isNumericType(int sqlType) {
        return sqlType == Types.INTEGER ||
                sqlType == Types.BIGINT ||
                sqlType == Types.SMALLINT ||
                sqlType == Types.TINYINT ||
                sqlType == Types.NUMERIC ||
                sqlType == Types.DECIMAL ||
                sqlType == Types.FLOAT ||
                sqlType == Types.DOUBLE ||
                sqlType == Types.REAL;
    }

    private static String escapeIdentifier(String identifier) {
        // Simple escaping - wrap in double quotes
        // In real implementation, might need database-specific handling
        if (identifier.contains(" ") || identifier.contains("-")) {
            return "\"" + identifier.replace("\"", "\"\"") + "\"";
        }
        return identifier;
    }

    /**
     * Generate a default table name from the query result.
     */
    public static String generateTableName(QueryResult result) {
        if (!result.getColumns().isEmpty()) {
            // Try to guess from first column or use generic name
            return "exported_data";
        }
        return "table_data";
    }
}
