package querycraft.util;

import querycraft.model.ColumnInfo;
import querycraft.model.DatabaseType;
import querycraft.service.StreamingQueryService.StreamingExporter;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.sql.Types;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class SqlStreamingExporter implements StreamingExporter {

    private final File file;
    private final String tableName;
    private final DatabaseType dbType;
    private final int batchSize;
    private final boolean useTransaction;
    private final SimpleDateFormat dateFormat;
    
    private Writer writer;
    private List<ColumnInfo> columns;
    private String insertPrefix;
    private int currentRowIndex = 0;

    public SqlStreamingExporter(File file, String tableName, DatabaseType dbType) {
        this(file, tableName, dbType, 1000, true);
    }

    public SqlStreamingExporter(File file, String tableName, DatabaseType dbType, int batchSize, boolean useTransaction) {
        this.file = file;
        this.tableName = tableName != null ? tableName : "exported_data";
        this.dbType = dbType;
        this.batchSize = batchSize;
        this.useTransaction = useTransaction;
        this.dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    }

    @Override
    public void start(List<ColumnInfo> columns) throws Exception {
        this.columns = columns;
        this.writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8);

        if (columns.isEmpty()) {
            writer.write("-- No columns found in result set\n");
            return;
        }

        // Write header
        writer.write("-- Generated by QueryCraft (Streaming)\n");
        writer.write("-- Generated at: " + dateFormat.format(new Date()) + "\n");
        writer.write("-- Source table: " + tableName + "\n\n");

        if (useTransaction) {
            writer.write(dbType.getBeginTransaction() + "\n\n");
        }

        // Database specific pre-insert adjustments
        String preInsert = dbType.getPreInsertSql(tableName);
        if (preInsert != null && !preInsert.isEmpty()) {
            writer.write(preInsert + "\n\n");
        }

        // Precompute prefix
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO ").append(dbType.escapeIdentifier(tableName)).append(" (");
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(dbType.escapeIdentifier(columns.get(i).getName()));
        }
        sb.append(") VALUES ");
        this.insertPrefix = sb.toString();
    }

    @Override
    public void writeRow(Object[] row) throws Exception {
        if (columns.isEmpty()) return;

        if (currentRowIndex > 0 && currentRowIndex % batchSize == 0) {
            writer.write(";\n\n");
            writer.write(insertPrefix);
        } else if (currentRowIndex > 0 && currentRowIndex % batchSize != 0) {
            writer.write(",\n");
        } else {
            // First row in the file
            writer.write(insertPrefix);
        }

        writer.write(buildValuesClause(row));
        currentRowIndex++;
    }

    @Override
    public void finish() throws Exception {
        if (writer != null) {
            if (currentRowIndex > 0) {
                writer.write(";\n"); // Finish last batch
            }

            // Database specific post-insert adjustments
            String postInsert = dbType.getPostInsertSql(tableName);
            if (postInsert != null && !postInsert.isEmpty()) {
                writer.write("\n" + postInsert + "\n");
            }

            if (useTransaction) {
                writer.write("\n" + dbType.getCommitTransaction() + "\n");
            }
            writer.flush();
            writer.close();
        }
    }

    @Override
    public void abort() {
        if (writer != null) {
            try {
                if (useTransaction) writer.write("\n-- EXPORT ABORTED\nROLLBACK;\n");
                writer.close();
            } catch (Exception ignored) {}
        }
    }

    private String buildValuesClause(Object[] row) {
        StringBuilder sb = new StringBuilder("(");
        for (int i = 0; i < row.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(formatSqlValue(row[i], columns.get(i)));
        }
        sb.append(")");
        return sb.toString();
    }

    private String formatSqlValue(Object value, ColumnInfo columnInfo) {
        if (value == null) return "NULL";
        int sqlType = columnInfo.getSqlType();
        if (isNumericType(sqlType)) return value.toString();
        if (value instanceof java.sql.Timestamp) return "'" + value.toString() + "'";
        if (value instanceof java.sql.Date) return "'" + value.toString() + "'";
        if (value instanceof java.sql.Time) return "'" + value.toString() + "'";
        if (value instanceof Date) return "'" + dateFormat.format((Date) value) + "'";
        if (value instanceof Boolean) return dbType.formatBoolean((Boolean) value);

        String strValue = value.toString();
        return "'" + strValue.replace("'", "''") + "'";
    }

    private boolean isNumericType(int sqlType) {
        return sqlType == Types.INTEGER || sqlType == Types.BIGINT || sqlType == Types.SMALLINT ||
               sqlType == Types.TINYINT || sqlType == Types.NUMERIC || sqlType == Types.DECIMAL ||
               sqlType == Types.FLOAT || sqlType == Types.DOUBLE || sqlType == Types.REAL;
    }
}
