package querycraft.export;

import querycraft.model.ColumnInfo;
import querycraft.model.DatabaseType;
import querycraft.model.QueryResult;
import querycraft.util.SqlValueFormatter;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * Strategy implementation for generating SQL INSERT statements from query results.
 */
public class SqlInsertGenerator implements DataExporter {

    private static final int DEFAULT_BATCH_SIZE = 1000;
    
    private final String tableName;
    private final DatabaseType dbType;
    private final int batchSize;
    private final boolean useTransaction;

    public SqlInsertGenerator(String tableName, DatabaseType dbType) {
        this(tableName, dbType, DEFAULT_BATCH_SIZE, true);
    }

    public SqlInsertGenerator(String tableName, DatabaseType dbType, int batchSize, boolean useTransaction) {
        this.tableName = tableName != null ? tableName : "exported_data";
        this.dbType = dbType;
        this.batchSize = batchSize;
        this.useTransaction = useTransaction;
    }

    @Override
    public void export(QueryResult result, File file) throws IOException {
        generate(result, file, this.tableName, this.batchSize, this.useTransaction, this.dbType);
    }

    @Override
    public String getFileExtension() {
        return "sql";
    }

    @Override
    public String getDisplayName() {
        return "SQL INSERT Statements";
    }

    /**
     * Legacy static method for backward compatibility.
     */
    public static void generate(QueryResult result, File file, String tableName, DatabaseType dbType) throws IOException {
        generate(result, file, tableName, DEFAULT_BATCH_SIZE, true, dbType);
    }

    /**
     * Generate SQL INSERT statements with options.
     */
    public static void generate(QueryResult result, File file, String tableName,
                                 int batchSize, boolean useTransaction, DatabaseType dbType) throws IOException {

        try (Writer writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {

            List<ColumnInfo> columns = result.getColumns();

            if (columns.isEmpty()) {
                writer.write("-- No columns found in result set\n");
                return;
            }

            // Write header comment
            writer.write("-- Generated by QueryCraft\n");
            writer.write("-- Generated at: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()) + "\n");
            writer.write("-- Source table: " + tableName + "\n");
            writer.write("-- Row count: " + result.getRowCount() + "\n");
            writer.write("\n");

            // Start transaction
            if (useTransaction) {
                writer.write(dbType.getBeginTransaction() + "\n\n");
            }

            // Database specific pre-insert adjustments (e.g., IDENTITY_INSERT for MSSQL)
            String preInsert = dbType.getPreInsertSql(tableName);
            if (preInsert != null && !preInsert.isEmpty()) {
                writer.write(preInsert + "\n\n");
            }

            // Generate INSERT statements
            List<Object[]> rows = result.getRows();
            String insertPrefix = buildInsertPrefix(tableName, columns, dbType);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            for (int i = 0; i < rows.size(); i++) {
                if (i > 0 && i % batchSize == 0) {
                    writer.write("\n");
                }

                Object[] row = rows.get(i);
                String values = buildValuesClause(row, columns, sdf, dbType);
                writer.write(insertPrefix + values + ";\n");
            }

            // Database specific post-insert adjustments
            String postInsert = dbType.getPostInsertSql(tableName);
            if (postInsert != null && !postInsert.isEmpty()) {
                writer.write("\n" + postInsert + "\n");
            }

            // End transaction
            if (useTransaction) {
                writer.write("\n" + dbType.getCommitTransaction() + "\n");
            }
        }
    }

    /**
     * Generate batch INSERT statements (multiple VALUES per INSERT).
     */
    public static void generateBatchInserts(QueryResult result, File file, String tableName,
                                            int rowsPerInsert, DatabaseType dbType) throws IOException {

        try (Writer writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {

            List<ColumnInfo> columns = result.getColumns();

            if (columns.isEmpty()) {
                writer.write("-- No columns found in result set\n");
                return;
            }

            // Write header
            writer.write("-- Generated by QueryCraft\n");
            writer.write("-- Generated at: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()) + "\n");
            writer.write("-- Source table: " + tableName + "\n");
            writer.write("-- Row count: " + result.getRowCount() + "\n");
            writer.write("\n");

            writer.write(dbType.getBeginTransaction() + "\n\n");

            // Database specific pre-insert adjustments
            String preInsert = dbType.getPreInsertSql(tableName);
            if (preInsert != null && !preInsert.isEmpty()) {
                writer.write(preInsert + "\n\n");
            }

            String insertPrefix = buildInsertPrefix(tableName, columns, dbType);
            List<Object[]> rows = result.getRows();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            for (int i = 0; i < rows.size(); i += rowsPerInsert) {
                writer.write(insertPrefix);

                int endIndex = Math.min(i + rowsPerInsert, rows.size());
                for (int j = i; j < endIndex; j++) {
                    if (j > i) {
                        writer.write(",\n");
                    }
                    writer.write(buildValuesClause(rows.get(j), columns, sdf, dbType));
                }

                writer.write(";\n\n");
            }

            // Database specific post-insert adjustments
            String postInsert = dbType.getPostInsertSql(tableName);
            if (postInsert != null && !postInsert.isEmpty()) {
                writer.write(postInsert + "\n\n");
            }

            writer.write(dbType.getCommitTransaction() + "\n");
        }
    }

    private static String buildInsertPrefix(String tableName, List<ColumnInfo> columns, DatabaseType dbType) {
        return SqlValueFormatter.buildInsertPrefix(tableName, columns, dbType);
    }

    private static String buildValuesClause(Object[] row, List<ColumnInfo> columns, SimpleDateFormat sdf, DatabaseType dbType) {
        return SqlValueFormatter.buildValuesClause(row, columns, sdf, dbType);
    }


    /**
     * Generate a default table name from the query result.
     */
    public static String generateTableName(QueryResult result) {
        if (!result.getColumns().isEmpty()) {
            // Try to guess from first column or use generic name
            return "exported_data";
        }
        return "table_data";
    }
}
